DROP SCHEMA IF EXISTS "v2016" CASCADE;
CREATE SCHEMA "v2016";
DROP TABLE IF EXISTS "v2016".path_status;
DROP TABLE IF EXISTS "v2016".rhybcp_status;
DROP TABLE IF EXISTS "v2016".employment;
DROP TABLE IF EXISTS "v2016".health_status;
DROP TABLE IF EXISTS "v2016".affiliation;
DROP TABLE IF EXISTS "v2016".site;
DROP TABLE IF EXISTS "v2016".inventory;
DROP TABLE IF EXISTS "v2016".funder;
DROP TABLE IF EXISTS "v2016".enrollment_coc;
DROP TABLE IF EXISTS "v2016".medicalassistance;
DROP TABLE IF EXISTS "v2016".domesticviolence;
DROP TABLE IF EXISTS "v2016".disabilities;
DROP TABLE IF EXISTS "v2016".residentialmoveindate;
DROP TABLE IF EXISTS "v2016".dateofengagement;
DROP TABLE IF EXISTS "v2016".incomeandsources;
DROP TABLE IF EXISTS "v2016".noncashbenefits;
DROP TABLE IF EXISTS "v2016".healthinsurance;
DROP TABLE IF EXISTS "v2016".exithousingassessment;
DROP TABLE IF EXISTS "v2016".housingassessmentdisposition;
DROP TABLE IF EXISTS "v2016".exit;
DROP TABLE IF EXISTS "v2016".coc;
DROP TABLE IF EXISTS "v2016".project;
DROP TABLE IF EXISTS "v2016".enrollment;
DROP TABLE IF EXISTS "v2016".organization;
DROP TABLE IF EXISTS "v2016".client_veteran_info;
DROP TABLE IF EXISTS "v2016".client;
DROP TABLE IF EXISTS "v2016".bulk_upload_activity;
DROP TABLE IF EXISTS "v2016".export;
DROP TABLE IF EXISTS "v2016".source;
DROP TABLE IF EXISTS "v2016".exitRHY;
DROP TABLE IF EXISTS "v2016".exitPath;
DROP TABLE IF EXISTS "v2016".bulk_upload_error;
CREATE TABLE "v2016".source (
  "id" uuid NOT NULL,
  "export" TEXT,
  "sourcetype" TEXT,
  "softwarename" TEXT,
  "softwareVersion" VARCHAR(50),
  "sourceContactEmail" TEXT,
  "sourceContactExtension" TEXT,
  "sourceContactFirst" VARCHAR(50),
  "sourceContactLast" VARCHAR(50),
  "sourceContactPhone" VARCHAR(12),
  "sourceID" TEXT,
  "sourceName" VARCHAR(50),
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "source_pkey" PRIMARY KEY (id)
);
CREATE TABLE "v2016".export (
  "id" uuid NOT NULL,
  "export_date" TIMESTAMP,
  "start_date" TIMESTAMP,
  "end_date" TIMESTAMP,
  "exportPeriodType" TEXT,
  "exportDirective" TEXT,
  "source_id" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "export_pkey" PRIMARY KEY (id),
  CONSTRAINT source_fkey FOREIGN KEY (source_id) REFERENCES "v2016".source(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".organization (
  "id" uuid NOT NULL,
  "organizationname" TEXT,
  "organizationcommonname" TEXT,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "organization_pkey" PRIMARY KEY (id)
);
CREATE TABLE "v2016".project (
  "id" uuid NOT NULL,
  "projectname" TEXT,
  "continuumproject" "v2016".no_yes,
  "projecttype" "v2016".project_type,
  "trackingmethod" "v2016".tracking_method,
  "targetpopulation" "v2016".target_population_type,
  "projectcommonname" TEXT,
  "organizationid" uuid,
  "date_created" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "project_group_code" VARCHAR(8),
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "project_pk" PRIMARY KEY (id),
  CONSTRAINT "organization_project_fkey" FOREIGN KEY (organizationid) REFERENCES "v2016".organization(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".client (
  "id" uuid NOT NULL,
  "dedup_client_id" uuid,
  "first_name" CHAR(50),
  "middle_name" CHAR(50),
  "last_name" CHAR(50),
  "name_suffix" CHAR(50),
  "name_data_quality" "v2016".name_data_quality,
  "ssn" CHAR(9),
  "ssn_data_quality" "v2016".ssn_data_quality,
  "dob" TIMESTAMP,
  "dob_data_quality" "v2016".dob_data_quality,
  "gender" "v2016".gender,
  "other_gender" TEXT,
  "ethnicity" "v2016".ethnicity,
  "race" "v2016".race,
  "veteran_status" "v2016".veteran_status,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT client_pk PRIMARY KEY (id)
);
CREATE TABLE "v2016".client_veteran_info (
  "id" uuid NOT NULL,
  "year_entrd_service" INT,
  "year_seperated" INT,
  "world_war_2" "v2016".five_val_dk_refused,
  "korean_war" "v2016".five_val_dk_refused,
  "vietnam_war" "v2016".five_val_dk_refused,
  "desert_storm" "v2016".five_val_dk_refused,
  "afghanistan_oef" "v2016".afghanistanoef,
  "iraq_oif" "v2016".five_val_dk_refused,
  "iraq_ond" "v2016".five_val_dk_refused,
  "other_theater" "v2016".five_val_dk_refused,
  "military_branch" "v2016".military_branch,
  "discharge_status" "v2016".discharge_status,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "client_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT veteran_info_pk PRIMARY KEY (id),
  CONSTRAINT veteran_info_client_fk FOREIGN KEY ("client_id") REFERENCES "v2016".client(id) MATCH SIMPLE
);
CREATE TABLE "v2016".enrollment (
  "id" uuid NOT NULL,
  "projectentryid" uuid,
  "entrydate" TIMESTAMP,
  "householdid" TEXT,
  "relationshiptohoh" "v2016".relationship_to_head_of_household,
  "otherresidenceprior" TEXT,
  "residencePrior" "v2016".residence_prior,
  "losunderthreshold" "v2016".no_yes,
  "previousStreetESSH" "v2016".no_yes,
  "residencePriorlengthofstay" "v2016".residence_prior_length_of_stay,
  "disablingCondition" "v2016".five_val_dk_refused,
  "housingstatus" "v2016".housing_status,
  "entryFromStreetESSH" INT,
  "dateToStreetESSH" INT,
  "timesHomelesspastthreeyears" "v2016".times_homeless_past_3_years,
  "monthsHomelessPastThreeYears" "v2016".months_homeless_past_3_years,
  "projectid" uuid,
  "client_id" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "chronicHomeless" boolean DEFAULT FALSE,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "enrollment_pkey" PRIMARY KEY (id),
  CONSTRAINT enrollment_client_fk FOREIGN KEY ("client_id") REFERENCES "v2016".client(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT enrollment_project_fk FOREIGN KEY ("projectid") REFERENCES "v2016".project(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".path_status (
  "id" uuid NOT NULL,
  "date_of_status" TIMESTAMP,
  "client_enrolled_in_path" BIGINT,
  "reason_not_enrolled" "v2016".reason_not_enrolled,
  "enrollmentid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT path_status_pk PRIMARY KEY (id),
  CONSTRAINT "enrollment_path_status_fk_key" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".entrySSVF (
  "id" uuid NOT NULL,
  "enrollmentid" uuid,
  "percentami" "v2016".percentAMI,
  "last_permanent_street" CHAR(50),
  "last_permanent_city" CHAR(50),
  "last_permanent_state" CHAR(50),
  "last_permanent_zip" CHAR(50),
  "address_data_quality" INT,
  "urgent_referral" "v2016".no_yes,
  "timeToHousingLoss" "v2016".timeToHousingLoss,
  "zeroincome" "v2016".no_yes,
  "annualpercentami" "v2016".annualpercentami,
  "financialchange" "v2016".no_yes,
  "householdchange" "v2016".no_yes,
  "evictionhistory" "v2016".evictionhistory,
  "subsidyatrisk" "v2016".no_yes,
  "literalHomelessHistory" "v2016".literalHomelessHistory,
  "disablehoh" "v2016".no_yes,
  "criminalrecord" "v2016".no_yes,
  "sexoffender" "v2016".no_yes,
  "dependendunder6" "v2016".no_yes,
  "singleparent" "v2016".no_yes,
  "hh5plus" "v2016".no_yes,
  "iraqafghanistan" "v2016".no_yes,
  "femvet" "v2016".no_yes,
  "thresholdscore" INT,
  "ervisits" "v2016".crisisServicesUse,
  "jailnights" "v2016".crisisServicesUse,
  "hospitalnights" "v2016".crisisServicesUse,
  "hp_screen_score" INT,
  "vamc_staction" CHAR(50),
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT entrySSVF_pk PRIMARY KEY (id),
  CONSTRAINT "enrollment_entrySSVF_fk_key" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".entryRHY (
  "id" uuid NOT NULL,
  "enrollmentid" uuid,
  "sexual_orientation" "v2016".sexual_orientation,
  "formerly_ward_child_welfr_forest_care" "v2016".formerly_ward_child_welfr_forest_care,
  "years_child_welfr_forest_care" "v2016".years_child_welfr_forest_care,
  "months_child_welfr_forest_care" INT,
  "formerly_ward_of_juvenile_justice" "v2016".formerly_ward_of_juvenile_justice,
  "years_juvenile_justice" "v2016".years_juvenile_justice,
  "months_juvenile_justice" "v2016".years_juvenile_justice,
  "house_hold_dynamics" "v2016".house_hold_dynamics,
  "sexual_orientatiion_gender_identity_youth" "v2016".sexual_orientation_gender_identity_Youth,
  "sexual_orientatiion_gender_identity_family_mbr" "v2016".sexual_orientatiion_gender_identity_family_mbr,
  "housing_issues_youth" "v2016".housing_issues_youth,
  "housing_issues_family_mbrily_mbr" "v2016".housing_issues_family_mbr,
  "school_education_issues_youth" "v2016".school_educational_issues_youth,
  "school_education_issues_family_mbr" "v2016".school_education_issues_family_mbr,
  "unemployement_youth" "v2016".unemployment_youth,
  "unemployement_family_mbr" "v2016".unemployement_family_mbr,
  "mental_health_issues_youth" "v2016".mental_health_issues_youth,
  "mental_health_issues_family_mbrily_mbr" "v2016".mental_health_issues_family_mbrily_mbr,
  "health_issues_youth" "v2016".health_issues_youth,
  "health_issues_family_mbrily_mbr" "v2016".health_issues_family_mbr,
  "physical_disability_youth" "v2016".physical_disability_youth,
  "physical_disability_family_mbr" "v2016".physical_disability_family_mbr,
  "mental_disability_youth" "v2016".mental_disability_youth,
  "mental_disability_family_mbrily_mbr" "v2016".mental_disability_family_mbr,
  "abuse_and_neglect_youth" "v2016".abuse_and_neglect_youth,
  "abuse_and_neglect_family_mbr" "v2016".abuse_and_neglect_family_mbr,
  "alcohol_drug_abuse_youth" "v2016".alcohol_drug_abuse_youth,
  "alcohol_drug_abuse_family_mbr" "v2016".alcohol_drug_abuse_family_mbr,
  "insufficient_income_to_support_youth" "v2016".insufficient_income_to_support_youth,
  "active_military_parent" "v2016".active_military_parent,
  "incarcerated_parent" "v2016".incarcerated_parent,
  "incarcerated_parent_status" "v2016".incarcerated_parent_status,
  "referral_source" INT,
  "count_out_reach_referral_approaches" INT,
  "exchange_for_sex" INT,
  "exchange_for_sex_past_three_months" "v2016".exchange_for_sex_past_three_months,
  "count_of_exchange_for_sex" "v2016".count_of_exchange_for_sex,
  "asked_of_forced_to_exchange_for_sex" "v2016".asked_of_forced_to_exchange_for_sex,
  "asked_of_forced_to_exchange_for_sex_past_3_months" "v2016".asked_of_forced_to_exchange_for_sex_past_3_months,
  "work_place_violence_threat" "v2016".work_place_violence_threats,
  "work_place_promise_difference" "v2016".work_place_promise_difference,
  "coerced_to_continue_work" "v2016".coerced_to_continue_work,
  "labor_exploit_past_three_months" INT,
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT entryRHY_pk PRIMARY KEY (id),
  CONSTRAINT "enrollment_entryRHY_fk_key" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".enrollment_coc (
  "id" uuid NOT NULL,
  "enrollmentid" uuid,
  "client_code" CHAR(20),
  "householdid" TEXT,
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "enrollment_coc_pkey" PRIMARY KEY (id),
  CONSTRAINT "enrollment_coc_fk_key" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".service_fa_referral (
  "id" uuid NOT NULL,
  "enrollmentid" uuid,
  "dateProvided" TIMESTAMP,
  "service_category" INT,
  "funder_list" INT,
  "type_provided" INT,
  "other_type_provided" TEXT,
  "sub_type_provided" INT,
  "fa_amount" NUMERIC(10, 2),
  "referral_outcome" INT,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT service_fa_referral_pk PRIMARY KEY (id),
  CONSTRAINT "service_fa_referral_fk_key" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".schoolstatus (
  "id" uuid NOT NULL,
  "information_date" TIMESTAMP,
  "school_status" "v2016".school_status,
  "enrollmentid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT school_status_pk PRIMARY KEY (id),
  CONSTRAINT "enrollment_schoolstatus_fk_key" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".employment (
  "id" uuid NOT NULL,
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "employed" "v2016".five_val_dk_refused,
  "employment_type" "v2016".employment_type,
  "not_employed_reason" "v2016".not_employed_reason,
  "enrollmentid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT employment_pk PRIMARY KEY (id),
  CONSTRAINT "enrollment_employment_fk_key" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".health_status (
  "id" uuid NOT NULL,
  "enrollmentid" uuid,
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "health_category" "v2016".health_category,
  "health_status" "v2016".health_status_type,
  "due_date" TIMESTAMP,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT health_status_pk PRIMARY KEY (id),
  CONSTRAINT "enrollment_health_status_fk_key" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".contact (
  "id" uuid NOT NULL,
  "contact_date" TIMESTAMP,
  "contact_location" "v2016".contact_location,
  "enrollmentid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT contact_pk PRIMARY KEY (id),
  CONSTRAINT "enrollment_health_status_fk_key" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".affiliation (
  "id" uuid NOT NULL,
  "projectid" uuid,
  "resprojectid" TEXT,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "affiliation_pkey" PRIMARY KEY (id),
  CONSTRAINT "affiliation_project_fkey" FOREIGN KEY (projectid) REFERENCES "v2016".project(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".coc (
  "id" uuid NOT NULL,
  "coccode" TEXT,
  "projectid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "coc_pkey" PRIMARY KEY (id),
  CONSTRAINT "coc_projectid_fkey" FOREIGN KEY (projectid) REFERENCES "v2016".project(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".site (
  "id" uuid NOT NULL,
  "address" VARCHAR(100),
  "city" VARCHAR(50),
  "geocode" INT,
  "principal_site" "v2016".no_yes,
  "coc_id" uuid,
  "STATE" "v2016".STATE,
  "zip" TEXT,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "site_pkey" PRIMARY KEY (id),
  CONSTRAINT "site_coc_fkey" FOREIGN KEY (coc_id) REFERENCES "v2016"."coc" (id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".inventory (
  "id" uuid NOT NULL,
  "householdtype" "v2016".house_hold_type,
  "bedtype" "v2016".bed_type,
  "availabilty" "v2016".availability,
  "unitinventory" INT,
  "ch_bed_inventory" INT,
  "vet_bed_inventory" INT,
  "youth_bed_inventory" INT,
  "youth_age_group" INT,
  "inventorystartdate" TIMESTAMP,
  "inventoryenddate" TIMESTAMP,
  "hmisparticipatingbeds" INT,
  "coc_id" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "user_id" uuid,
  "informationDate" TIMESTAMP,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "inventory_pkey" PRIMARY KEY (id),
  CONSTRAINT "inventory_cocid_fkey" FOREIGN KEY (coc_id) REFERENCES "v2016"."coc" (id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".funder (
  "id" uuid NOT NULL,
  "enddate" TIMESTAMP,
  "funder" "v2016".federal_partner_components,
  "grantid" uuid,
  "projectid" uuid,
  "startdate" TIMESTAMP,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "funder_pkey" PRIMARY KEY (id),
  CONSTRAINT "funder_projectid_fkey" FOREIGN KEY ("projectid") REFERENCES "v2016".project(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".rhybcp_status (
  "id" uuid NOT NULL,
  "status_date" TIMESTAMP,
  "fysb_youth" "v2016".no_yes,
  "reason_no_services" "v2016".fysb_rsn_not_providing_srvcs,
  "enrollmentid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT rhybcp_status_pk PRIMARY KEY (id),
  CONSTRAINT "enrollment_rhybcp_status_fk_key" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".medicalassistance (
  "id" uuid NOT NULL,
  "hivaidsassistance" "v2016".five_val_dk_refused,
  "nohivaidsassistancereason" "v2016".no_medical_assistance_reason,
  "adap" "v2016".five_val_dk_refused,
  "noadapreason" "v2016".no_medical_assistance_reason,
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "enrollmentid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "medicalassistance_pkey" PRIMARY KEY (id),
  CONSTRAINT "medicalassistance_enrollmentid_fkey" FOREIGN KEY (enrollmentid) REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".domesticviolence (
  "id" uuid NOT NULL,
  "domesticviolencevictim" "v2016".five_val_dk_refused,
  "enrollmentid" uuid,
  "whenoccurred" "v2016".when_dom_violence_occurred,
  "currently_fleeing" INT,
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "domesticviolence_pkey" PRIMARY KEY (id),
  CONSTRAINT "domesticviolence_enrollmentid_fkey" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".disabilities (
  "id" uuid NOT NULL,
  "disabilitytype" "v2016".disability_type,
  "disabilityresponse" INT,
  "indefiniteandimpairs" "v2016".five_val_dk_refused,
  "documentationonfile" "v2016".no_yes,
  "receivingservices" "v2016".five_val_dk_refused,
  "pathhowconfirmed" "v2016".path_how_confirmed,
  "pathsmiinformation" "v2016".path_smi_info_how_confirmed,
  "enrollmentid" uuid,
  "tcellcountavailable" INT,
  "tcellcount" INT,
  "tcellcountsource" CHAR(8),
  "viral_load_available" INT,
  "viral_load" INT,
  "viral_load_source" CHAR(8),
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "disabilities_pkey" PRIMARY KEY (id),
  CONSTRAINT "disabilities_enrollmentid_fkey" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".residentialmoveindate (
  "id" uuid NOT NULL,
  "inpermanenthousing" "v2016".no_yes,
  "enrollmentid" uuid,
  "residentialmoveindate" TIMESTAMP,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "residentialmoveindate_pkey" PRIMARY KEY (id),
  CONSTRAINT "residentialmoveindate_enrollmentid_fkey" FOREIGN KEY (enrollmentid) REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE "v2016".dateofengagement (
  "id" uuid NOT NULL,
  "dateofengagement" TIMESTAMP,
  "enrollmentid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "dateofengagement_pkey" PRIMARY KEY (id),
  CONSTRAINT "dateofengagement_enrollmentid_fkey" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".entryRHSP (
  "id" uuid NOT NULL,
  "worst_housing_situation" INT,
  "enrollmentid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "entryRHSP_pkey" PRIMARY KEY (id),
  CONSTRAINT "entryRHSP_enrollmentid_fkey" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".education (
  "id" uuid NOT NULL,
  "lastgradecompleted" "v2016".last_grade_completed,
  "school_status" "v2016".school_status,
  "enrollmentid" uuid,
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "education_pkey" PRIMARY KEY (id),
  CONSTRAINT "education_fkey" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".incomeandsources (
  "alimony" "v2016".no_yes,
  "alimonyamount" NUMERIC(15, 3),
  "childsupport" "v2016".no_yes,
  "childsupportamount" NUMERIC(15, 3),
  "earned" "v2016".no_yes,
  "earnedamount" NUMERIC(15, 3),
  "ga" "v2016".no_yes,
  "gaamount" NUMERIC(15, 3),
  "id" uuid NOT NULL,
  "incomefromanysource" "v2016".five_val_dk_refused,
  "othersource" "v2016".no_yes,
  "othersourceamount" NUMERIC(15, 3),
  "othersourceidentify" TEXT,
  "pension" "v2016".no_yes,
  "pensionamount" NUMERIC(15, 3),
  "privatedisability" "v2016".no_yes,
  "privatedisabilityamount" NUMERIC(15, 3),
  "enrollmentid" uuid,
  "socsecretirement" "v2016".no_yes,
  "socsecretirementamount" NUMERIC(15, 3),
  "ssdi" "v2016".no_yes,
  "ssdiamount" NUMERIC(15, 3),
  "ssi" "v2016".no_yes,
  "ssiamount" NUMERIC(15, 3),
  "tanf" "v2016".no_yes,
  "tanfamount" NUMERIC(15, 3),
  "totalmonthlyincome" NUMERIC(15, 3),
  "unemployment" "v2016".no_yes,
  "unemploymentamount" NUMERIC(15, 3),
  "vadisabilitynonservice" "v2016".no_yes,
  "vadisabilitynonserviceamount" NUMERIC(15, 3),
  "vadisabilityservice" "v2016".no_yes,
  "vadisabilityserviceamount" NUMERIC(15, 3),
  "workerscomp" "v2016".no_yes,
  "workerscompamount" NUMERIC(15, 3),
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "incomeandsources_pkey" PRIMARY KEY (id),
  CONSTRAINT "incomeandsources_enrollmentid_fkey" FOREIGN KEY (enrollmentid) REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".noncashbenefits (
  "id" uuid NOT NULL,
  "benefitsfromanysource" "v2016".five_val_dk_refused,
  "othersource" "v2016".no_yes,
  "othersourceidentify" TEXT,
  "othertanf" "v2016".no_yes,
  "enrollmentid" uuid,
  "rentalassistanceongoing" "v2016".no_yes,
  "rentalassistancetemp" "v2016".no_yes,
  "snap" "v2016".no_yes,
  "tanfchildcare" "v2016".no_yes,
  "tanftransportation" "v2016".no_yes,
  "wic" "v2016".no_yes,
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "noncashbenefits_pkey" PRIMARY KEY (id),
  CONSTRAINT "noncashbenefits_enrollmentid_fkey" FOREIGN KEY (enrollmentid) REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".healthinsurance (
  "id" uuid NOT NULL,
  "insurancefromanysource" "v2016".five_val_dk_refused,
  "medicaid" "v2016".no_yes,
  "nomedicaidreason" "v2016".no_health_insurance_reason,
  "medicare" "v2016".no_yes,
  "nomedicarereason" "v2016".no_health_insurance_reason,
  "schip" "v2016".no_yes,
  "noschipreason" "v2016".no_health_insurance_reason,
  "vamedicalservices" "v2016".no_yes,
  "novamedreason" "v2016".no_health_insurance_reason,
  "employerprovided" INT,
  "noemployerprovidedreason" "v2016".no_health_insurance_reason,
  "cobra" INT,
  "nocobrareason" "v2016".no_health_insurance_reason,
  "privatepay" "v2016".no_yes,
  "noprivatepayreason" "v2016".no_health_insurance_reason,
  "statehealthinadults" "v2016".no_yes,
  "nostatehealthinsreason" "v2016".no_health_insurance_reason,
  "other_insurance" "v2016".no_yes,
  "other_insurance_identify" TEXT,
  "indianhealthservices" "v2016".no_yes,
  "noindianhealthservicesreason" "v2016".no_health_insurance_reason,
  "enrollmentid" uuid,
  "information_date" TIMESTAMP,
  "datacollectionstage" "v2016".datacollectionstage,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "healthinsurance_pkey" PRIMARY KEY (id),
  CONSTRAINT "healthinsurance_enrollmentid_fkey" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".EXIT (
  "id" uuid NOT NULL,
  "destination" "v2016".destination,
  "exitdate" TIMESTAMP,
  "otherdestination" TEXT,
  "enrollmentid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "exit_pkey" PRIMARY KEY (id),
  CONSTRAINT "exit_enrollmentid_fkey" FOREIGN KEY ("enrollmentid") REFERENCES "v2016".enrollment(id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".exitPath (
  "id" uuid NOT NULL,
  "connection_with_soar" "v2016".connection_with_soar,
  "exitid" uuid,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "exit_path_pkey" PRIMARY KEY (id),
  CONSTRAINT "exit_fkey" FOREIGN KEY (exitid) REFERENCES "v2016".EXIT (id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".exithousingassessment (
  "id" uuid NOT NULL,
  "exitid" uuid,
  "housingassessment" "v2016".housing_assmnt_exit,
  "subsidyinformation" "v2016".subsidy_information,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "exithousingassessment_pkey" PRIMARY KEY (id),
  CONSTRAINT "exithousingassessment_fkey" FOREIGN KEY (exitid) REFERENCES "v2016".EXIT (id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".exitRHY (
  "id" uuid NOT NULL,
  "exitid" uuid,
  "project_completion_status" "v2016".project_completion_status,
  "early_exit_reason" "v2016".early_exit_reason,
  "family_reunification_achieved" "v2016".family_reunification_achieved,
  "written_after_care_plan" "v2016".written_after_care_plan,
  "assistance_main_stream_benefits" "v2016".assistance_main_stream_benefits,
  "permenant_housing_placement" "v2016".permanent_housing_placement,
  "temp_shelter_placement" "v2016".temp_shelter_placement,
  "exit_counseling" "v2016".exit_counseling,
  "further_followup_services" "v2016".further_followup_services,
  "scheduled_followup_contacts" "v2016".scheduled_followup_contacts,
  "resource_package" "v2016".resource_package,
  "other_aftercare_plan_or_action" "v2016".other_aftercare_plan_or_action,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "exitRHY_pkey" PRIMARY KEY (id),
  CONSTRAINT "exitRHY_fkey" FOREIGN KEY (exitid) REFERENCES "v2016".EXIT (id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".housingassessmentdisposition (
  "id" uuid NOT NULL,
  "assessmentdisposition" "v2016".assessment_disposition,
  "exitid" uuid,
  "otherdisposition" TEXT,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_created_from_source" TIMESTAMP,
  "date_updated_from_source" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT "housingassessmentdisposition_pkey" PRIMARY KEY (id),
  CONSTRAINT "housingassessmentdisposition_exitid_fkey" FOREIGN KEY (exitid) REFERENCES "v2016"."exit" (id) MATCH SIMPLE ON UPDATE NO action ON DELETE NO action
);
CREATE TABLE "v2016".hud_coc_report_question_7 (
  "id" BIGINT PRIMARY KEY NOT NULL,
  "first_name" BIGINT,
  "last_name" BIGINT,
  "ssn" BIGINT,
  "dob" BIGINT,
  "race" BIGINT,
  "ethnicity" BIGINT,
  "gender" BIGINT,
  "veteran_status" BIGINT,
  "disabling_cond" BIGINT,
  "residence_prior_to_entry" BIGINT,
  "zip_lpa" BIGINT,
  "housing_stat_entry" BIGINT,
  "income_entry" BIGINT,
  "income_exit" BIGINT,
  "non_cash_benefits_entry" BIGINT,
  "non_cash_benefits_exit" BIGINT,
  "physical_disability_entry" BIGINT,
  "devlopmental_disability_entry" BIGINT,
  "chronic_health_condition_entry" BIGINT,
  "hiv_aids_entry" BIGINT,
  "mental_health_entry" BIGINT,
  "substance_abuse_entry" BIGINT,
  "domestic_violence_entry" BIGINT,
  "destination" BIGINT,
  "total_clients" BIGINT,
  "total_adults" BIGINT,
  "total_unaccompanied_youth" BIGINT,
  "total_leavers" BIGINT,
  "del_flag" CHAR(3),
  "status_flag" CHAR(3)
);
CREATE TABLE "v2016".bulk_upload_activity (
  "id" serial NOT NULL,
  "bulk_upload_id" BIGINT,
  "TABLE_NAME" VARCHAR(100),
  "records_processed" BIGINT,
  "description" TEXT,
  "project_group_code" VARCHAR(8),
  "date_created" TIMESTAMP,
  "date_updated" TIMESTAMP,
  "inserted" BIGINT,
  "updated" BIGINT,
  "user_id" uuid,
  "export_id" uuid,
  "parent_id" uuid,
  "version" INT,
  "source_system_id" TEXT,
  "deleted" boolean DEFAULT FALSE,
  "active" boolean DEFAULT TRUE,
  "sync" boolean DEFAULT FALSE,
  CONSTRAINT export_fkey FOREIGN KEY (export_id) REFERENCES "v2016".export(id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT bulk_upload_activity_pk PRIMARY KEY (id)
);
CREATE TABLE "v2016".bulk_upload_error (
  "id" BIGINT NOT NULL,
  "model_id" uuid,
  "bulk_upload_ui" BIGINT,
  "TABLE_NAME" TEXT,
  "project_group_code" VARCHAR(8),
  "source_system_id" TEXT,
  "TYPE" VARCHAR(8),
  "error_description" TEXT,
  "date_created" TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT bulk_upload_error_pkey PRIMARY KEY (id)
);
CREATE SEQUENCE "v2016".error_sequence INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;
